# Generated by Django 4.0.6 on 2022-08-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('KANAGAWA', 'Kanagawa')], max_length=16)),
                ('event_type', models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('NATURE', 'Nature'), ('ART', 'Art'), ('EXPERIENCE', 'Experience'), ('HOT_SPRING', 'Hot_spring'), ('SHRINES_TEMPLES', 'Shrines_temples'), ('FOOD', 'Food'), ('POWER_SPOT', 'Power_spot')], max_length=16)),
                ('inn_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('RYOKAN', 'Ryokan'), ('DORMITORY', 'Domitory')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('time', models.TimeField()),
                ('picture', models.ImageField(upload_to='')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
    ]
