# Generated by Django 4.0.6 on 2022-08-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='inn_type',
        ),
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_type',
            field=models.CharField(choices=[('HOKKAIDO', 'Hokkaido'), ('KANAGAWA', 'Kanagawa'), ('OKINAWA', 'Okinawa')], max_length=16),
        ),
        migrations.AlterField(
            model_name='route',
            name='event_type',
            field=models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('FOOD', 'Food'), ('HOT_SPRING', 'HotSpring')], max_length=16),
        ),
        migrations.AlterField(
            model_name='spot',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.route'),
        ),
    ]
