import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>にわか旅のしおり</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className={styles.main}>
        {/* <div className="top"> */}
        {/*   <img src="top_image.jpeg" alt="Snow" width="100%" /> */}
        {/*   <div className="centered">お一人様旅行をもっと手軽に。</div> */}
        {/* </div> */}

        <p className={styles.description}>
          1人で旅行に行きたいけど、計画するのが面倒。
          <br />
          そう思ったら「にわか旅のしおり」を使ってみませんか？
        </p>

        <Link href="/search">
          <button className="button">検索してみる</button>
        </Link>

        <div className={styles.description}>
          <h1>会員登録のメリット</h1>
          <br />
          <ul>
            <li>お気に入り登録できる</li>
            <li>ボタンひとつで完全決済</li>
            <li>旅程やチケットがアプリ一つに</li>
          </ul>
        </div>

        <Link href="/register">
          <button className="button">会員登録はこちら</button>
        </Link>
        <Link href="/login">
          <a>ログインはこちら</a>
        </Link>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
