import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <form className="form">
          <div>
            <p>メールアドレス</p>
            <p>
              <input
                type="email"
                name="email"
                size="30"
                placeholder="xxx@mail.com"
              />
            </p>
          </div>
          <div>
            <p>パスワード</p>
            <p>
              <input type="password" name="password" size="30" placeholder="" />
            </p>
          </div>
          <div className="center-button">
            <Link href="/mypage">
              <button className="button">ログイン</button>
            </Link>
          </div>
        </form>
      </main>
    </div>
  )
}
