import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Mypage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>マイページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <div>
          <h2>ようこそ、翔さん</h2>
          <Link href="/search">
            <button className="button">＋旅程を探す</button>
          </Link>
        </div>
        <div className="mypage-content">
          <div className="box">
            <h2>予約したプラン</h2>
            <p>日程 8/5</p>
            <p>旅行地 神奈川</p>
            <p>金額 6500円</p>
            <p>
              <Link href="/plan-detail">
                <a className="link">＞プラン詳細</a>
              </Link>
            </p>
          </div>
          <div className="box">
            <h2>お気に入りプラン</h2>
            <p>アウトドア-神奈川</p>
            <p>
              <Link href="/plan-detail">
                <a className="link">＞プラン詳細</a>
              </Link>
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}
