import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Plandetail() {
    return(
        <div className={styles.container}>
            <Head>
            <title>プラン詳細</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h2>予約プラン詳細</h2>
                <div className="spot">
                    <div className="spot_time">
                        <p>スポット1</p>
                        <p>到着時刻　10:00</p>
                        <p>出発時刻　12:00</p>
                    </div>
                    <div className="spot_image">
                        <Image src="/top_image.jpeg" width={200} height={200}/>
                    </div>
                    <p className="spot_description">
                        リフレッシュできます
                    </p>
                </div>
                ↓電車で移動
                <div className="spot">
                    <div className="spot_time">
                        <p>スポット2</p>
                        <p>到着時刻　13:00</p>
                        <p>出発時刻　17:00</p>
                    </div>
                    <div className="spot_image">
                        <Image src="/top_image.jpeg" width={200} height={200}/>
                    </div>
                    <p className="spot_description">
                        リフレッシュできます
                    </p>
                </div>
                ↓電車で移動
                <div className="spot">
                    <div className="spot_time">
                        <p>スポット3</p>
                        <p>到着時刻　18:00</p>
                        <p>出発時刻　21:00</p>
                    </div>
                    <div className="spot_image">
                        <Image src="/top_image.jpeg" width={200} height={200}/>
                    </div>
                    <p className="spot_description">
                        リフレッシュできます
                    </p>
                </div>
            </main>
        </div>
    );
}